#!/bin/bash

cat>temp_fuse
files=($* temp_fuse)

i=1
x=1
while test $x -eq 1
do
	j=0
	newline=""
	while test $j -lt ${#files[*]}
	do
		o=$i
		o+="p"
		new=$(cat ${files[$j]} | sed -n "$o")
		if [ "$new" ]
		then
			new+="	"
		fi
	newline+=$new
	j=$(($j+1))
	done
	newline=`echo "$newline" | sed 's/	$//g'`
if [ "$newline" ]
then
	echo "$newline" >> temp_result
else
	x=0
fi
i=$(($i+1))
done


cat temp_result
rm temp_result
rm temp_fuse
