#!/bin/bash
text=$(echo $* | tr -d " " | sed 's/[x+]/ & /g')
sum=$(echo $text | sed 's/[x+]/)&(0/g' | sed 's/[|]/+1/g' | sed 's/^.*$/(0&)/g' | tr "x" "*" | bc)
tandestokers=$(echo $text | tr "|x+" "122" | sed 's/[^0-9]\|\([0-9]\)/\1/g' | sed 's/./+&/g' | sed 's/^.*$/0&/' | bc )
echo "$text = $sum ($tandestokers tandestokers)"
